import 'prismjs'
import 'prismjs/plugins/line-numbers/prism-line-numbers.js'
import 'prismjs/plugins/line-numbers/prism-line-numbers.min.css'
import 'prismjs/components/prism-javascript.min.js'
import 'prismjs/components/prism-css.min.js'
import 'prismjs/components/prism-markup.min.js'
import 'prismjs/components/prism-typescript.min.js'
import 'prismjs/components/prism-jsx.min.js'
import 'prismjs/components/prism-tsx.min.js'
import 'prismjs/components/prism-bash.min.js'
import 'prismjs/components/prism-csv.min.js'
import 'prismjs/components/prism-json.min.js'
import 'prismjs/components/prism-java.min.js'
import 'prismjs/components/prism-docker.min.js'
import 'prismjs/components/prism-yaml.min.js'
import 'prismjs/themes/prism-okaidia.min.css'

export {}
