name: Deploy @iwsio/forms-demo

on:
  workflow_call:
    secrets:
      FLY_API_TOKEN:
        required: true

jobs:
  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: git fetch && git pull origin main
      - run: flyctl deploy --build-arg PUBLIC_URL="/" --build-arg GITHUB_SHA="$GITHUB_SHA"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
