name: PR to Main - @iwsio/forms

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'forms/**'
jobs:
  tests:
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    uses: ./.github/workflows/forms-test.yaml
    secrets: inherit
