name: "@iwsio/forms: PUSH to main"

on:
  push:
    branches: [ main ]
    paths:
      - 'forms/**'

jobs:
  tests:
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    uses: iwsllc/workflows/.github/workflows/test.yaml@v2
    with:
      node-version-file: '.nvmrc'
      install-command: npm ci
      build-command: npm run build -w forms
      test-command: npm test
  version:
    needs: tests
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    uses: iwsllc/workflows/.github/workflows/version.yaml@v1
    with:
      ref: main
      node-version-file: '.nvmrc'
      version-command: npm version patch -ws --include-workspace-root
  publish:
    needs: version
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    uses: iwsllc/workflows/.github/workflows/publish.yaml@v1
    with:
      ref: main
      registry-url: https://registry.npmjs.org
      node-version-file: '.nvmrc'
      install-command: npm ci -w forms
      build-command: npm run build -w forms
      publish-command: npm publish -w forms --access public
    secrets:
      # This token is used for reading npm packages; use when private packages are used
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  deploy_demo:
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    needs: version
    uses: ./.github/workflows/demo-deploy.yaml
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
